// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/.DS_Store",
    "/favicon.png",
    "/images/buoy_logo.svg",
    "/images/buoy_logo_dark.png",
    "/images/buoy_logo_dark.svg",
    "/images/cm_logo.svg",
    "/images/example-home.png",
    "/images/rss.svg",
    "/robots.txt",
    "/search/api.json",
    "/videos/hero-video-optimized.mp4",
    "/videos/hero-video-optimized.webm"
  ]
};

// ../../../../../opt/homebrew/lib/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/jt/buoy-fish-tech/website/BUOY.fish/.wrangler/tmp/pages-4TkImc/bundledWorker-0.709106530599461.mjs";
import { isRoutingRuleMatch } from "/opt/homebrew/lib/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/jt/buoy-fish-tech/website/BUOY.fish/.wrangler/tmp/pages-4TkImc/bundledWorker-0.709106530599461.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=jxhi05o2jti.js.map
